server:
  port: 8080
spring:
  redis:
    timeout: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
remain:
  time: 12